### ISSUE TITLE
correlation plot b/ lisa

### ISSUE THREAD

**Issue by fmtlisa** [merlynjocol/Covid_Dashboards_OpenData#11]
MERLYN COMMENTS:
1. The last dataframe is 'covid-w', this dataframe not include the weird names countries. I already change it in the correlation chart Lisa made, then the explanation will change.
2. I think a correlation chart is great if we see others variables such as smoking person, obesity, GINI. We got those variables in the original data-set, when we start doing it in streamlit we can add those variables, then people can interact with the dashboard and make this own conclusions.
3. Another comment is about the palette, colors are inverse, we should improve the scale of the palette, dark colors for the highest correlation (>0.8). In the next chart, I use the inverse palette ('flare')
Check documentation about colors here: https://seaborn.pydata.org/tutorial/color_palettes.html?highlight=palette

**Comment by fmtlisa** [comment]
Lisa answers: I agree with everything you said, I changed to the green color palette, and I will be glad to invest the correlation with the smoking and everything.

**Comment by fmtlisa** [comment]
logical high correlations: new_cases & new_cases_smoothed, total_deaths &total_cases, new_deaths & new_deaths_smoothed, people_fully_vaccinated &total_vaccinations &people_vaccinated

**Comment by fmtlisa** [comment]
interesting correlations:  new_deaths is only correlated by 0.2 with the new_vaccinations: the number of deaths has almost no link with the number of vaccinations. That may be caused by a numeric bias: vaccinations started very late, and that culd explain those numbers. On another note, total_vaccinations is correlated with total_deaths by 0.5, and by 0.7 with people_vaccinated: that means the more vaccinations/vaccinated people is not linked to less deaths, it is quite the opposite (more vaccinations goes along with more deaths). That does not underline the effectiveness of the vaccination.

**Comment by fmtlisa** [comment]
added the correlation with all the available variables, need: do the conclusions/interpretation

**Comment by pierrepo** [comment]
The idea of this dashboard is more to follow number of cases and deaths per country vs time than to find correlations between variable. Please try to keep correlations for an extra later step.

**Comment by fmtlisa** [comment]
![Capture d’écran (307)](https://user-images.githubusercontent.com/73339052/119656015-7e315c00-be2a-11eb-8342-1bc01d9bb3a6.png)
![Uploading Capture d’écran (308).png…]()
