### ISSUE TITLE
Requirements for the dashboards

### ISSUE THREAD

**Issue by merlynjocol** [merlynjocol/Covid_Dashboards_OpenData#24]
Your dashboard should be interactive and allow the user to:
 - Select which countries to display (among a pre-defined list).
- Select which time period to display.
- Select which variable(s) to display: 
- number / cumulated number / 7-day rolling average
- of confirmed cases / deaths / (recovered)
- Upon parameter selection, graphics should be updated dynamically.

You could also implement peak detection with the first numeric derivative.

**Comment by merlynjocol** [comment]
### Visualization
- Dashboard displays graphics of Covid-19 cases or deaths vs time.
- Dashboard displays graphics of Covid-19 cases or deaths for several countries.
- Data are normalized with respect to the number of inhabitants per country.
- Peak (wave) detection is implemented.

###  Interaction
- User can select which country to display (among a predefined list of countries).
- User can display many countries in the same graphic.
- User can select the color of the line.
- User can select to display Covid-19 cases or deaths.
- User can select the time frame to display.

**Comment by fmtlisa** [comment]
The new check list is the following, i think it is the one we have to follow rn:
![image](https://user-images.githubusercontent.com/73339052/120798749-1ec80000-c53e-11eb-809e-c5b98289f127.png)

**Comment by fmtlisa** [comment]
just added the smoother on a week charts

**Comment by fmtlisa** [comment]
added the json file

**Comment by fmtlisa** [comment]
no color hcoice but choice of date to add

**Comment by merlynjocol** [comment]
I see an error in the code. 
The variables  the charts for **ca_pms** and **de_pms**  are not created yet.  I will do it

**Comment by merlynjocol** [comment]
> 
> 
> no color hcoice but choice of date to add

I don't  understand what is the change you did about the color or date?

**Comment by fmtlisa** [comment]
> > no color hcoice but choice of date to add
> 
> I don't understand what is the change you did about the color or date?

I did none, I was just taking notes about what Pierre said during class :) we no longer have to make a choice of color, but we do have to do a choice of date

**Comment by merlynjocol** [comment]
ok,  keep this Issue for solving the visualization and interactions Tasks we need to achieve

> 
> 
> > > no color hcoice but choice of date to add
> > 
> > 
> > I don't understand what is the change you did about the color or date?
> 
> I did none, I was just taking notes about what Pierre said during class :) we no longer have to make a choice of color, but we do have to do a choice of date

This interaction task is already mentioned above  (time frame display)

**Comment by merlynjocol** [comment]
It's already working: 

__Visualization__
- [x] Dashboard displays graphics of Covid-19 cases or deaths vs time.
- [x] Dashboard displays graphics of Covid-19 cases or deaths for several countries.
- [x] Data are normalized with respect to the number of inhabitants per country.
- [  ] **Peak (wave) detection is implemented for cumulative number of cases or deaths.**
- [x] 7-day rolling average for the absolute (non-cumulative) number of cases or deaths.

__Interaction__
- [x] User can select which country to display (among a predefined list of countries).
- [x] User can display many countries in the same graphic.
- [x] User can select to display Covid-19 cases or deaths.
- [  ] **User can select to display or not the peak detection (for cumulative numbers only).**
- [x] User can select to display or not the 7-day rolling average (for absolute numbers only).
- [  ] **User can select the time frame to display.**  _


**NOTE:  The Time Period still not working, I created a dataframe for the interval selected but still the bug**
 
Everything is in the **Branch V5**
