### ISSUE TITLE
select the datas we want

### ISSUE THREAD

**Issue by fmtlisa** [merlynjocol/Covid_Dashboards_OpenData#5]

**Comment by fmtlisa** [comment]
john hopkins --> everything has to be merged, that's so long
we'll use the csse data set

**Comment by fmtlisa** [comment]
variables: 
- death rate
- number of cases
- recovered cases

By country 
By date

foundable here:

https://github.com/CSSEGISandData/COVID-19/tree/master/csse_covid_19_data/csse_covid_19_time_series

**Comment by fmtlisa** [comment]
merge the 3 global files:
- time_series_covid19_recovered_global.csv
- time_series_covid19_deaths_global.csv
- time_series_covid19_confirmed_global.csv

**Comment by kozload** [comment]
_confirmed_.csv as the solution for our 'merged file' issue... ok

**Comment by merlynjocol** [comment]
Options: 

John Hopkins 
'https://github.com/CSSEGISandData/COVID-19/raw/master/csse_covid_19_data/csse_covid_19_daily_reports/05-18-2021.csv

Our world Data 
https://github.com/owid/covid-19-data/blob/master/public/data/owid-covid-data.csv?raw=true

**Comment by pierrepo** [comment]
Hey :wave: 
I was not aware of *Our World in Data* dataset. It might be easier to use since it aggregates multiple date sources (and the one from JHU).
Before taking a decision, please look at the data carefully...

**Comment by fmtlisa** [comment]
Okay, let's go with the Our World Dataset, and select the columns we will need.
