### ISSUE TITLE
Documentation in Readme

### ISSUE THREAD

**Issue by merlynjocol** [merlynjocol/Covid_Dashboards_OpenData#6]

**Comment by merlynjocol** [comment]
Add the dataset used in Readme.md

**Comment by fmtlisa** [comment]
i added a description of the variables

**Comment by fmtlisa** [comment]
The readme shall cointrain guidelines to explicity install all required dependencies for the project

**Comment by fmtlisa** [comment]
the readme file shall contain instructions on how to locally run the dashbaord

**Comment by fmtlisa** [comment]
> The readme shall cointrain guidelines to explicity install all required dependencies for the project

done

**Comment by fmtlisa** [comment]
> the readme file shall contain instructions on how to locally run the dashbaord

done

**Comment by kozload** [comment]
I will add  the requirements.txt file with dependencies to finish up with metadata...

**Comment by kozload** [comment]
> I will add the requirements.txt file with dependencies to finish up with metadata...

**Comment by fmtlisa** [comment]
i added an introduction on the document

**Comment by merlynjocol** [comment]
**The README.**

- [x] md file is present at the root of the GitHub repo.
- [x] The README.md file states where the data come from (with a link to the original repo).
- [x] The README.md file contains guidelines to explicitly install all required dependencies for the project.
- [x] The README.md file contains instructions on how to locally run the dashboard.
- [x] The LICENSE file contains a valid open-source license.
- [x] The requirements.txt (for pip) or environment.yml (for conda) file to install all required dependencies at once.

**Comment by kozload** [comment]
- [x] The README.md file contains a Software Heritage button (link)
