### ISSUE TITLE
Skecth of visual charts and graphs for the app

### ISSUE THREAD

**Issue by fmtlisa** [merlynjocol/Covid_Dashboards_OpenData#8]

**Comment by fmtlisa** [comment]
merlyn : first analysis, data cleaning, code for visualisation with pyplot.express

**Comment by fmtlisa** [comment]
lisa: added plots

**Comment by pierrepo** [comment]
Hey team5 :wave: 
Do not hesitate to add snaphosts of your plots in the issue. It's seamless with GitHub, a copy and paste will make it.

**Comment by fmtlisa** [comment]
[
![Capture d’écran (299)](https://user-images.githubusercontent.com/73339052/119655896-5e019d00-be2a-11eb-9c82-265fe1e8f9d1.png)
![Capture d’écran (300)](https://user-images.githubusercontent.com/73339052/119655901-6063f700-be2a-11eb-9c32-a73c13c85af2.png)
![Capture d’écran (302)](https://user-images.githubusercontent.com/73339052/119655922-678b0500-be2a-11eb-8ca0-2749d7e6ce99.png)
![Capture d’écran (303)](https://user-images.githubusercontent.com/73339052/119655926-68bc3200-be2a-11eb-8e7c-e782fbda577b.png)
![Capture d’écran (304)](https://user-images.githubusercontent.com/73339052/119655933-6954c880-be2a-11eb-9059-15bf1bc4de8c.png)
![Capture d’écran (305)](https://user-images.githubusercontent.com/73339052/119655940-6a85f580-be2a-11eb-8634-dd372375deca.png)
![Capture d’écran (306)](https://user-images.githubusercontent.com/73339052/119655941-6b1e8c00-be2a-11eb-811a-a7f8b9ad5fbf.png)
![Capture d’écran (307)](https://user-images.githubusercontent.com/73339052/119655946-6bb72280-be2a-11eb-8e72-b78fb218a0c5.png)
![Capture d’écran (308)](https://user-images.githubusercontent.com/73339052/119655948-6bb72280-be2a-11eb-8389-b62b7fd6e7bc.png)
![Capture d’écran (301)](https://user-images.githubusercontent.com/73339052/119655951-6c4fb900-be2a-11eb-911b-43a14e007f59.png)









](url)

**Comment by pierrepo** [comment]
Thanks for nice and visual outputs.
For a start, I prefer you keep the time in the x-axis for all graphics.

**Comment by merlynjocol** [comment]
Adding the first chart. 
type: linechart
x: date
y: total cases / total deaths
Interaction with multiple countries and different analysis (cases /deaths)

**Comment by merlynjocol** [comment]
![image](https://user-images.githubusercontent.com/45790494/119967154-5964f200-bfac-11eb-9232-2cdad82a61eb.png)
